/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.gson.JsonPrimitive;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Clinica extends javax.swing.JFrame {

    /**
     * Creates new form clinica
     */
    public Clinica() {
        initComponents();
        genero.setUI(Propiedades.createUI(rootPane));
        departamentCbx.setUI(Propiedades.createUI(rootPane));
        distritCbx.setUI(Propiedades.createUI(rootPane));
        provinceCbx.setUI(Propiedades.createUI(rootPane));
        this.loadData();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        nombre = new rojeru_san.RSMTextFull();
        apellido = new rojeru_san.RSMTextFull();
        dni = new rojeru_san.RSMTextFull();
        fecha = new rojeru_san.componentes.RSDateChooser();
        ecivil = new rojeru_san.RSMTextFull();
        edad = new rojeru_san.RSMTextFull();
        alergia = new rojeru_san.RSMTextFull();
        genero = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        departamentCbx = new javax.swing.JComboBox<>();
        distritCbx = new javax.swing.JComboBox<>();
        provinceCbx = new javax.swing.JComboBox<>();
        departamento = new javax.swing.JLabel();
        provincia = new javax.swing.JLabel();
        distrito = new javax.swing.JLabel();
        direccionn = new javax.swing.JLabel();
        direccion = new rojeru_san.RSMTextFull();
        telefonoo = new javax.swing.JLabel();
        correoo = new javax.swing.JLabel();
        correo = new rojeru_san.RSMTextFull();
        telefono = new rojeru_san.RSMTextFull();
        pesoo = new javax.swing.JLabel();
        alturaa = new javax.swing.JLabel();
        altura = new rojeru_san.RSMTextFull();
        peso = new rojeru_san.RSMTextFull();
        rSButtonRiple1 = new rojeru_san.RSButtonRiple();
        rSButtonRiple2 = new rojeru_san.RSButtonRiple();
        rSButtonRiple4 = new rojeru_san.RSButtonRiple();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        rSMTextFull12 = new rojeru_san.RSMTextFull();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clinica");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        jSeparator1.setForeground(new java.awt.Color(0, 145, 252));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 104, 172));
        jLabel1.setText("Datos del Paciente");

        nombre.setPlaceholder("Nombre");
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        apellido.setPlaceholder("Apellido");

        dni.setPlaceholder("DNI");

        ecivil.setPlaceholder("Estado Civil");

        edad.setPlaceholder("Edad");

        alergia.setPlaceholder("Alergia");
        alergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alergiaActionPerformed(evt);
            }
        });

        genero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Masculino", "Femenino" }));
        genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 112, 192));
        jLabel2.setText("Género:");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 112, 192));
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 112, 192));
        jLabel4.setText("Apellido:");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 112, 192));
        jLabel5.setText("DNI:");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 112, 192));
        jLabel6.setText("Fecha:");

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 112, 192));
        jLabel7.setText("Estado Civil:");

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 112, 192));
        jLabel8.setText("Edad:");

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 112, 192));
        jLabel9.setText("Alergia:");

        departamentCbx.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        departamentCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        departamentCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departamentCbxActionPerformed(evt);
            }
        });

        distritCbx.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        distritCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        distritCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distritCbxActionPerformed(evt);
            }
        });

        provinceCbx.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        provinceCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        provinceCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinceCbxActionPerformed(evt);
            }
        });

        departamento.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        departamento.setForeground(new java.awt.Color(0, 112, 192));
        departamento.setText("Departamento:");

        provincia.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        provincia.setForeground(new java.awt.Color(0, 112, 192));
        provincia.setText("Provincia:");

        distrito.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        distrito.setForeground(new java.awt.Color(0, 112, 192));
        distrito.setText("Distrito:");

        direccionn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        direccionn.setForeground(new java.awt.Color(0, 112, 192));
        direccionn.setText("Dirección:");

        direccion.setPlaceholder("Dirección");

        telefonoo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        telefonoo.setForeground(new java.awt.Color(0, 112, 192));
        telefonoo.setText("Telefono:");

        correoo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        correoo.setForeground(new java.awt.Color(0, 112, 192));
        correoo.setText("Correo:");

        pesoo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        pesoo.setForeground(new java.awt.Color(0, 112, 192));
        pesoo.setText("Peso:");

        alturaa.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        alturaa.setForeground(new java.awt.Color(0, 112, 192));
        alturaa.setText("Altura:");

        altura.setPlaceholder("Altura");

        peso.setPlaceholder("Peso:");

        rSButtonRiple1.setText("Guardar");
        rSButtonRiple1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple1ActionPerformed(evt);
            }
        });

        rSButtonRiple2.setBackground(new java.awt.Color(255, 0, 0));
        rSButtonRiple2.setText("Eliminar");
        rSButtonRiple2.setColorHover(new java.awt.Color(255, 51, 51));

        rSButtonRiple4.setBackground(new java.awt.Color(255, 204, 0));
        rSButtonRiple4.setText("Editar");
        rSButtonRiple4.setColorHover(new java.awt.Color(255, 204, 51));

        jTable1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jSeparator2.setForeground(new java.awt.Color(0, 145, 252));

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 112, 192));
        jLabel18.setText("Código:");

        rSMTextFull12.setPlaceholder("Código");
        rSMTextFull12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMTextFull12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(alergia, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(ecivil, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rSMTextFull12, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(departamento)
                                    .addGap(10, 10, 10)
                                    .addComponent(departamentCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(provincia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(provinceCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(distrito)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(distritCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(direccionn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(correoo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(telefonoo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(alturaa)
                                            .addGap(18, 18, 18)
                                            .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(80, 80, 80)
                                            .addComponent(rSButtonRiple1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(39, 39, 39)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(rSButtonRiple4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rSButtonRiple2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(61, 61, 61))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(pesoo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(271, 271, 271)
                                    .addComponent(jLabel19)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 19, Short.MAX_VALUE))))
            .addComponent(jSeparator2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSMTextFull12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ecivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(provincia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(departamentCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(provinceCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(distrito, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(distritCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(direccionn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(correoo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addComponent(alturaa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(telefonoo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pesoo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(peso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(altura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSButtonRiple1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonRiple4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonRiple2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generoActionPerformed

    private void alergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alergiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alergiaActionPerformed
    
    String cd;
    private void departamentCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departamentCbxActionPerformed
        // TODO add your handling code here:
        int idx = departamentCbx.getSelectedIndex();
        
        if (idx > 9) {
            cd = "" + idx;
        } else {
            cd = "0" + idx;
        }
        
        provinceCbx.removeAllItems();
        provinceCbx.addItem("Seleccionar");

        int cont = 0;
        int cont2 = 1;
        String let = cd + "0" + cont2;
        while (cont < loc.length) {
            String a = "";
            if (cont2 > 9) {
                a = cd + "" + cont2 + "00";
            } else {
                a = cd + "0" + cont2 + "00";
            }

            String count = loc[cont][0] + loc[cont][1];

            while (let.equals(count)) {
                String b = "";
                for (int j = 0; j < 4; j++) {
                    if (a.equals(b)) {
                        provinceCbx.addItem(loc[cont][j]);
                        cont2++;
                        if (cont2 > 9) {
                            let = cd + "" + cont2;
                        } else {
                            let = cd + "0" + cont2;
                        }
                    } else {
                        b = b + loc[cont][j];
                    }
                }
            }
            cont++;
        }
    }//GEN-LAST:event_departamentCbxActionPerformed

    private void distritCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distritCbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distritCbxActionPerformed

    private void provinceCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinceCbxActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        int idx = provinceCbx.getSelectedIndex();
        String cp;
        if (idx > 9) {
            cp = "" + idx;
        } else {
            cp = "0" + idx;
        }
        
        distritCbx.removeAllItems();
        distritCbx.addItem("Seleccionar");

        int cont = 0;
        int cont2 = 1;
        String let = cd + cp + "0" + cont2;
        while (cont < loc.length) {
            String a = "";
            if (cont2 > 9) {
                a = cd + cp + "" + cont2;
            } else {
                a = cd + cp + "0" + cont2;
            }

            String count = loc[cont][0] + loc[cont][1] + loc[cont][2];

            while (let.equals(count)) {
                String b = "";
                for (int j = 0; j < 4; j++) {
                    if (a.equals(b)) {
                        distritCbx.addItem(loc[cont][j]);
                        cont2++;
                        if (cont2 > 9) {
                            let = cd + cp + "" + cont2;
                        } else {
                            let = cd + cp + "0" + cont2;
                        }
                    } else {
                        b = b + loc[cont][j];
                    }
                }
            }
            cont++;
        }
    }//GEN-LAST:event_provinceCbxActionPerformed

    private void rSButtonRiple1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple1ActionPerformed
      
        try {
            Conexion conn = new Conexion();
                        
            String sqlQuery = "INSERT INTO CLINICA(id, nombre, apellido, dni, fecha, ecivil, edad, genero, alergia, departamento, provincia, distrito, direccion, correo, telefono, altura, peso) VALUES(NULL,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement consult = conn.getConnection().prepareStatement(sqlQuery);

            java.util.Date utilStartDate = fecha.getDatoFecha();
            java.sql.Date sqlStartDate = new java.sql.Date(utilStartDate.getTime());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String date = sdf.format(sqlStartDate);
            
            consult.setString(1, nombre.getText());
            consult.setString(2, apellido.getText());
            consult.setString(3, dni.getText());
            consult.setString(4, date);
            consult.setString(5, ecivil.getText());
            consult.setString(6, edad.getText());
            consult.setString(7, (String) genero.getSelectedItem());
            consult.setString(8, alergia.getText());
            consult.setString(9, (String) departamentCbx.getSelectedItem());
            consult.setString(10, (String) provinceCbx.getSelectedItem());
            consult.setString(11, (String) distritCbx.getSelectedItem());
            consult.setString(12, direccion.getText());
            consult.setString(13, correo.getText());
            consult.setString(14, telefono.getText());
            consult.setString(15, altura.getText());
            consult.setString(16, peso.getText());            
            System.out.println("sadasdasd");
            System.out.println("dfdfd");
            int result = consult.executeUpdate();
            if (result>0) {
                JOptionPane.showMessageDialog(null, "Se guardaron los datos con éxito!");
            } else{
                JOptionPane.showMessageDialog(null, "No se guardo los datos!");
            }
            
            java.util.Date f = new java.util.Date();
            nombre.setText("");
            apellido.setText("");
            dni.setText("");
            fecha.setDatoFecha(f);
            ecivil.setText("");
            edad.setText("");
            genero.setSelectedIndex(0);
            alergia.setText("");
            departamentCbx.setSelectedItem(0);
            provinceCbx.setSelectedItem(0);
            distritCbx.setSelectedItem(0);
            direccion.setText("");
            correo.setText("");
            telefono.setText("");
            peso.setText("");
            
        } catch (SQLException ex) {
            System.out.println("Ocurrió un error al conectar con base de datos:"+ex);
        }
    }//GEN-LAST:event_rSButtonRiple1ActionPerformed

    private void rSMTextFull12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMTextFull12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMTextFull12ActionPerformed
    
    int cant = 0;
    int cantT = 0;
    String[][] loc;
    
    //Obtener datos del archivo json
    public void dumpJSONElement(JsonElement elemento) {
        //System.out.println("---------------------------------------");
        if (elemento.isJsonObject()) {
            //System.out.println("Es objeto");
            JsonObject obj = elemento.getAsJsonObject();
            java.util.Set<java.util.Map.Entry<String, JsonElement>> entradas = obj.entrySet();
            java.util.Iterator<java.util.Map.Entry<String, JsonElement>> iter = entradas.iterator();
            while (iter.hasNext()) {
                java.util.Map.Entry<String, JsonElement> entrada = iter.next();
                //System.out.println("Clave: " + entrada.getKey());
                //System.out.println("Valor:");

                dumpJSONElement(entrada.getValue());
            }

        } else if (elemento.isJsonArray()) {
            JsonArray array = elemento.getAsJsonArray();
            //System.out.println("Es array. Numero de elementos: " + array.size());
            loc = new String[array.size()][4];
            java.util.Iterator<JsonElement> iter = array.iterator();
            while (iter.hasNext()) {
                JsonElement entrada = iter.next();
                dumpJSONElement(entrada);
            }
        } else if (elemento.isJsonPrimitive()) {
            //System.out.println("Es primitiva");
            JsonPrimitive valor = elemento.getAsJsonPrimitive();
            //System.out.println(cantT+":"+cant);
            //System.out.println("Es texto: " + valor.getAsString());
            loc[cantT][cant] = valor.getAsString();
            cant++;

            if (cant == 4) {
                cant = 0;
                cantT++;
            }
        } else if (elemento.isJsonNull()) {
            //System.out.println("Es NULL");
        } else {
            //System.out.println("Es otra cosa");
        }
    }
    
    //carga de datos para combobox departamento
    public void loadData() {
        JsonParser parser = new JsonParser();
        FileReader fr = null;
        try {
            fr = new FileReader(System.getProperty("user.dir")+"\\src\\utils\\ubigeo-peru.min.json");
        } catch (FileNotFoundException e) {

        }
        JsonElement datos = parser.parse(fr);
        //System.out.println(datos);
        dumpJSONElement(datos);
        int cont = 0;
        int cont2 = 1;
        String let = ("0" + cont2);
        while (cont < loc.length) {
            String a = "";
            if (cont2 > 9) {
                a = cont2 + "0000";
            } else {
                a = "0" + cont2 + "0000";
            }

            while (let.equals(loc[cont][0])) {
                String b = "";
                for (int j = 0; j < 4; j++) {
                    if (a.equals(b)) {
                        departamentCbx.addItem(loc[cont][j]);
                        cont2++;
                        if (cont2 > 9) {
                            let = "" + cont2;
                        } else {
                            let = "0" + cont2;
                        }
                    } else {
                        b = b + loc[cont][j];
                    }
                }
            }
            cont++;
        }
    }
    /**
     * @param args the command line arguments
     */
    
    //Estilos
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSMTextFull alergia;
    private rojeru_san.RSMTextFull altura;
    private javax.swing.JLabel alturaa;
    private rojeru_san.RSMTextFull apellido;
    private rojeru_san.RSMTextFull correo;
    private javax.swing.JLabel correoo;
    private javax.swing.JComboBox<String> departamentCbx;
    private javax.swing.JLabel departamento;
    private rojeru_san.RSMTextFull direccion;
    private javax.swing.JLabel direccionn;
    private javax.swing.JComboBox<String> distritCbx;
    private javax.swing.JLabel distrito;
    private rojeru_san.RSMTextFull dni;
    private rojeru_san.RSMTextFull ecivil;
    private rojeru_san.RSMTextFull edad;
    private rojeru_san.componentes.RSDateChooser fecha;
    private javax.swing.JComboBox<String> genero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private rojeru_san.RSMTextFull nombre;
    private rojeru_san.RSMTextFull peso;
    private javax.swing.JLabel pesoo;
    private javax.swing.JComboBox<String> provinceCbx;
    private javax.swing.JLabel provincia;
    private rojeru_san.RSButtonRiple rSButtonRiple1;
    private rojeru_san.RSButtonRiple rSButtonRiple2;
    private rojeru_san.RSButtonRiple rSButtonRiple4;
    private rojeru_san.RSMTextFull rSMTextFull12;
    private rojeru_san.RSMTextFull telefono;
    private javax.swing.JLabel telefonoo;
    // End of variables declaration//GEN-END:variables
}
